### ISSUE TITLE
Add an option in the config to make selecting a class compulsory

### ISSUE THREAD

**Issue by TechPro424** [Claralith/MobArena-Refabricated#16]
Add an option in the config to make selecting a class compulsory for players before they join the arena.

**Comment by Claralith** [comment]
Added in commit 59796d8513c1edf03552b7dd94a43aae4f7db1c9 and release [alpha-v1.3.3](https://github.com/Ommp/MobArena-Refabricated/releases/tag/alpha-v1.3.3).

**Comment by TechPro424** [comment]
Please add the command to the wiki

**Comment by Claralith** [comment]
@TechPro424 I have added the command to the new wiki. It can now be found [here](https://github.com/Ommp/MobArena-Refabricated/blob/1.18.2/docs/wiki/main.md).

**Comment by TechPro424** [comment]
I think it would be a good move to add it to the Class Setup page as well.
