### ISSUE TITLE
Add a countdown for players to join before the game starts.

### ISSUE THREAD

**Issue by TechPro424** [Claralith/MobArena-Refabricated#17]
When the first player selects a class and joins the arena, there should be a countdown (preferably configurable, the default should probably be 1 minute.) say 60 seconds, during which more players can join the arena. After the countdown is over, the game starts, and no more players can join. (But they can go to the spectator warp)

This would also open the possibility for a `minimumPlayerCount` option in the config (default could be 2), and the countdown starts only after the minimum number of players join, instead of after the 1st player

**Comment by Claralith** [comment]
I might try to implement a modified version of this, where the countdown only starts if all players that joined the lobby were ready and got transported into the arena (instead of just the first). The countdown will then either default to 5 or 10 seconds, during that time a player should be able to join the lobby, and if they do, the countdown stops and will start again when that player has readied up. If the countdown finishes, the first wave starts.

**Comment by Claralith** [comment]
There was an attempt to add this modified version in commit dff882d9e6ee2735e8c8ff60299a1210f4396fc9 and [alpha release 1.2.2](https://github.com/Ommp/MobArena-Refabricated/releases/tag/v1.2.2).
It will need to be tested to see if it works.

**Comment by TechPro424** [comment]
Command to set countdown, command to set min and max players,  command to restore a player's inventory is not there in wiki, please add it.

**Comment by Claralith** [comment]
https://github.com/Ommp/MobArena-Refabricated/issues/17#issuecomment-1256945742
> Command to set countdown, command to set min and max players, command to restore a player's inventory is not there in wiki, please add it.

Documentation for countdown, min and max commands added to the _Other Commands_ section at [Arena Setup](https://github.com/Ommp/MobArena-Refabricated/wiki/Arena-Setup).

Restore player inventory command documentation added to [Troubleshooting](https://github.com/Ommp/MobArena-Refabricated/wiki/Troubleshooting) page.

**Comment by TechPro424** [comment]
I guess that closes this issue?

**Comment by Claralith** [comment]
Not until it's confirmed that the countdown before the first wave starts actually allows players to join the lobby without any unexpected issues.

**Comment by Claralith** [comment]
Closing as joining before the first wave starts seems to work well. I tested it using a Carpet fake player, making the fake player join after the arena countdown just started, and the expected functionality was there.
