### ISSUE TITLE
Restore player's gamemode after leaving arena

### ISSUE THREAD

**Issue by Claralith** [Claralith/MobArena-Refabricated#18]
Currently, a player's gamemode is set to adventure upon joining a lobby and then set to survival after they have left the arena.
It would be better to restore the gamemode they had before entering the arena than to set it to survival.

**Comment by TechPro424** [comment]
I think Alpha 1.3.0 fixes this

**Comment by Claralith** [comment]
Added in 0381642d894daa8076184226c9a7ea745752ecea
