### ISSUE TITLE
Add commands to set min and max players

### ISSUE THREAD

**Issue by Claralith** [Claralith/MobArena-Refabricated#19]
Minimum players is currently set to 1 by default, maximum players defaults to 5. These should be configurable.

**Comment by TechPro424** [comment]
I think this issue can be closed, as release 1.2.3 adds this

**Comment by Claralith** [comment]
> I think this issue can be closed, as release 1.2.3 adds this

Yes, closing as it was added in commit https://github.com/Ommp/MobArena-Refabricated/commit/f0109d27bc9a591615109802d7a44b17d0af49c7 and release version [Alpha 1.2.3](https://github.com/Ommp/MobArena-Refabricated/releases/tag/alpha-v1.2.3)
