### ISSUE TITLE
Rewards

### ISSUE THREAD

**Issue by Claralith** [Claralith/MobArena-Refabricated#23]
The arena should be fun to play in on its own (intrinsic motivation), but a reward system is still important as it would add a lot more to the experience.

**The reward system will at least need:**

* A counter for how many waves a player survived.
* An option to configure rewards. For example 1 iron ingot for every 5 waves survived.
* Compatibility with the system that restores inventories after all players died or left the arena. If a player entered the arena with a full inventory, the way they receive rewards after leaving may need to be handled differently.

**Other things that may be considered:**
* Rewards for amount of kills, especially most kills if there are several players
* A chance system so that rewards for every _x_ wave can be randomised. For example: a 5% chance of getting a netherite chestplate for every _x_ wave.

The implementation for configuring the rewards will most likely be using the database instead of .json files as I am much more familiar with creating databases than configuration files. That way it's less likely to have bugs and is faster for me to implement. The configuration will therefore be through commands. Adding rewards could be done with a command like _/ma reward add "wave number"_  whilst holding an item.
~~**A list of features implemented will be added once it becomes relevant.**~~

**Comment by Claralith** [comment]
**Implemented features as of commit a2d6849c42dafed809ddc1bc9e36f5543ac1f0b8:**

- [x] Adding rewards using a command
- [x] Giving players rewards after they leave the arena or all players die
- [x] Deleting all the rewards for a wave in an arena using a command

As expected, if a player has a full inventory before entering the arena, they won't get any rewards when leaving unless the reward is an item they already had in the inventory. This will need to handled somehow. Some ways I think this could be solved:
1. Add a command that tries to give the players rewards (/ma rewards retrieve). This way, any rewards that don't make it into the player's inventory can still be retrieved. The reward items will need to be kept in memory until the player has received them all, or they could be saved into the database and deleted.
2. Drop the items onto the ground if the inventory has no space left. This would work well if there was a way to make sure only the player that deserved the reward could pick it up.
3. Show the player some sort of chest interface where they can take the rewards and throw away the things they have in their inventory that they want to replace.

Assuming number two is possible, I see it as the ideal solution.

**Comment by TechPro424** [comment]
I agree, use number 2

**Comment by TechPro424** [comment]
number 2 has been added in Alpha 1.4.0
I think this issue can be closed?

**Comment by Claralith** [comment]
> number 2 has been added in Alpha 1.4.0 I think this issue can be closed?

I was planning on closing this after making it possible for only the player that actually earned the reward to pick it up in case their inventory is full, but a new issue could be created for that.

**Comment by TechPro424** [comment]
Then maybe use method 1 instead of method 2? @Ommp
