### ISSUE TITLE
Add custom waves

### ISSUE THREAD

**Issue by Claralith** [Claralith/MobArena-Refabricated#29]
Custom waves can make arenas feel more unique by allowing players to set up arenas with more variety.
Inspiration for the features will be taken from the original [MobArena](https://github.com/garbagemule/MobArena/wiki/Setting-up-the-waves) plugin, but some of them might not be implemented.

Roadmap/Overview of features (may be changed):

- [x] Single wave configuration
    - [x] Specific wave number
    - [x] Wave type
    - [x] Monsters and their probability
    - [x] Fixed monster amount

- [x] Recurrent wave configuration
    - [x] Starts being available at specific wave
    - [x] Frequency (determines how often the wave can spawn)
    - [x] Priority (If two recurrent waves clash, the wave with the highest priority will spawn)
    - [x] Wave type
    - [x] Monsters and their probability
    - [x] Fixed monster amount

- [x] Single always prioritised over recurrent

**Comment by Claralith** [comment]
Below is an example of how a config would/could look for arenas with custom waves added.
```json
"test": {
      "Use custom spawns": false,
      "Monsters": [
        "minecraft:zombie",
        "minecraft:husk"
      ],
      "singleWaves": [
        {
          "wave": 1,
          "type": "BOSS",
          "monsters": {
            "minecraft:witch": 1,
            "minecraft:blaze": 1,
            "minecraft:creeper": 1,
            "minecraft:silverfish": 1,
            "minecraft:wolf": 1
          },
          "fixed": true
        }
      ],
      "recurrentWaves": [
        {
          "wave": 16,
          "frequency": 4,
          "priority": 1,
          "type": "DEFAULT",
          "monsters": {
            "minecraft:husk": 6
          },
          "fixed": false
        },
        {
          "wave": 10,
          "frequency": 1,
          "priority": 1,
          "type": "DEFAULT",
          "monsters": {
            "minecraft:skeleton": 5,
            "minecraft:wolf": 1,
            "minecraft:zombie": 3,
            "minecraft:pillager": 6,
            "minecraft:creeper": 1
          },
          "fixed": false
        },
        {
          "wave": 10,
          "frequency": 2,
          "priority": 1,
          "type": "SWARM",
          "monsters": {
            "minecraft:skeleton": 5,
            "minecraft:wolf": 2
          },
          "fixed": false
        },
        {
          "wave": 10,
          "frequency": 5,
          "priority": 1,
          "type": "SWARM",
          "monsters": {
            "minecraft:drowned": 5,
            "minecraft:wolf": 1
          },
          "fixed": false
        }
      ],
      "finalWave": 0
```

**Comment by YourRadiator** [comment]
monsieur

**Comment by Claralith** [comment]
Should work as of release [Alpha 1.4.0](https://github.com/Ommp/MobArena-Refabricated/releases/tag/alpha-v1.4.0)
